# Funding Configuration for Claude Code Branch Memory Manager

# GitHub Sponsors
github: [Davidcreador]

# Open Collective
# open_collective: claude-memory-manager

# Ko-fi
# ko_fi: davidcreador

# Custom funding URLs
custom: [
  "https://github.com/Davidcreador/claude-code-branch-memory-manager",
  "https://buymeacoffee.com/davidcreador"
]